const products=[
{id:1,name:'REALME 15 C',brand:'Realme',camera:'50 MP',cpu:'Helio G81-Ultra',ram:'8 GB',storage:'128 GB',battery:'6000 mAh',charge:'33 W',screen:'6.9” AMOLED',refresh:'120 Hz',image:'img/productos/REALMI15C.jpg',bestSeller:true,offer:false},
{id:2,name:'Infinix GT 30',brand:'Infinix',camera:'64 MP',cpu:'Dimensity 7400',ram:'12 GB',storage:'256 GB',battery:'5500 mAh',charge:'45 W',screen:'6.78” AMOLED',refresh:'144 Hz',image:'img/productos/INFINIXGT30.jpg',bestSeller:true,offer:true},
{id:3,name:'Infinix Note 50s',brand:'Infinix',camera:'64 MP',cpu:'Dimensity 7300 Ultimate',ram:'8 GB',storage:'256 GB',battery:'5500 mAh',charge:'45 W',screen:'6.78” AMOLED',refresh:'144 Hz',image:'img/productos/INFINIXNOTE50S.jpg',bestSeller:true,offer:true},
{id:4,name:'Infinix Hot 60 Pro+',brand:'Infinix',camera:'50 MP',cpu:'Helio G200',ram:'8 GB',storage:'256 GB',battery:'5160 mAh',charge:'45 W',screen:'6.78” AMOLED',refresh:'120 Hz',image:'img/productos/INFINIXHOT60PRO.jpg',bestSeller:true,offer:true},
{id:5,name:'Infinix Smart 10',brand:'Infinix',camera:'8 MP',cpu:'Unisoc T7250',ram:'6 GB',storage:'128 GB',battery:'5000 mAh',charge:'15 W',screen:'6.67” IPS LCD',refresh:'120 Hz',image:'img/productos/INFINIXSMART10.jpg',bestSeller:true,offer:true},
{id:6,name:'HONOR 200',brand:'Honor',camera:'50 MP',cpu:'Snapdragon 7 Gen 3',ram:'8 GB',storage:'256 GB',battery:'5200 mAh',charge:'100 W',screen:'6.7” AMOLED',refresh:'120 Hz',image:'img/productos/HONOR200.jpg',bestSeller:true,offer:true},
{id:7,name:'HONOR X5c',brand:'Honor',camera:'50 MP',cpu:'Helio G81',ram:'8 GB',storage:'128 GB',battery:'5250 mAh',charge:'15 W',screen:'6.74” LCD',refresh:'90 Hz',image:'img/productos/HONORX5C.jpg',bestSeller:true,offer:true},
{id:8,name:'Tecno Spark GO',brand:'Tecno',camera:'13 MP',cpu:'Unisoc T7250',ram:'4 GB',storage:'128 GB',battery:'5000 mAh',charge:'15 W',screen:'6.67” IPS',refresh:'120 Hz',image:'img/productos/TECNOSPARKGO2.jpg',bestSeller:true,offer:true},
{id:9,name:'Samsung Galaxy A26 5G',brand:'Samsung',camera:'50 MP',cpu:'Exynos 1380',ram:'8 GB',storage:'256 GB',battery:'5000 mAh',charge:'25 W',screen:'6.7” Super AMOLED',refresh:'120 Hz',image:'img/productos/SAMSUNGA26.jpg',bestSeller:true,offer:true},
{id:10,name:'Samsung Galaxy A16',brand:'Samsung',camera:'50 MP',cpu:'Helio G99',ram:'8 GB',storage:'256 GB',battery:'5000 mAh',charge:'25 W',screen:'6.7” Super AMOLED',refresh:'90 Hz',image:'img/productos/SAMSUNGA16.jpg',bestSeller:true,offer:true},
{id:11,name:'Samsung Galaxy A06',brand:'Samsung',camera:'50 MP',cpu:'Helio G85',ram:'4 GB',storage:'128 GB',battery:'5000 mAh',charge:'25 W',screen:'6.7” PLS LCD',refresh:'90 Hz',image:'img/productos/SAMSUNGA06.jpg',bestSeller:true,offer:true}
];
const technicalProducts=[
{name:'Samsung Galaxy A55 5G',camera:'Triple 50 MP',cpu:'Exynos 1480',battery:'5000 mAh',screen:'6.6” FHD+ Super AMOLED',tone:''},
{name:'Xiaomi Redmi Note 13 Pro',camera:'200 MP',cpu:'Snapdragon 7s Gen 2',battery:'5100 mAh',screen:'6.67” AMOLED',tone:'red'},
{name:'iPhone 14',camera:'Dual 12 MP',cpu:'Apple A15 Bionic',battery:'Hasta 20 h de video',screen:'6.1” Super Retina XDR',tone:'dark'},
{name:'Motorola Moto G54 5G',camera:'50 MP con OIS',cpu:'Dimensity 7020',battery:'5000 mAh',screen:'6.5” FHD+ 120 Hz',tone:''}
];
const catalog=document.getElementById('catalog'),promoCatalog=document.getElementById('promoCatalog'),emptyState=document.getElementById('emptyState'),headerSearch=document.getElementById('searchInput'),catalogSearch=document.getElementById('catalogSearch'),brandFilter=document.getElementById('brandFilter'),sortFilter=document.getElementById('sortFilter'),clearFilters=document.getElementById('clearFilters');
const compareModal=document.getElementById('comparison'),compareContainer=document.getElementById('compareContainer');let compare=[];let quickFilter='all';
const escapeHTML=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const wa=p=>`https://wa.me/573202147560?text=${encodeURIComponent(`Hola Creditel, estoy interesado en el ${p.name}. ¿Tienen disponibilidad y precio?`)}`;
function productCard(p){return `<article class="product"><span class="product-badge">${p.offer?'🔥 OFERTA':'✓ DISPONIBLE'}</span><div class="product-media"><img src="${escapeHTML(p.image)}" loading="lazy" alt="${escapeHTML(p.name)}" onerror="this.style.display='none';this.nextElementSibling.classList.remove('hidden')"><div class="product-placeholder hidden" aria-hidden="true"></div></div><div class="product-info"><div class="product-brand">${escapeHTML(p.brand)}</div><h3>${escapeHTML(p.name)}</h3><div class="specs"><div class="spec"><b>Cámara</b>${escapeHTML(p.camera)}</div><div class="spec"><b>Procesador</b>${escapeHTML(p.cpu)}</div><div class="spec"><b>Batería</b>${escapeHTML(p.battery)}</div><div class="spec"><b>Pantalla</b>${escapeHTML(p.screen)}</div></div><div class="product-footer"><a class="buy" href="${wa(p)}" target="_blank" rel="noopener">Consultar por WhatsApp</a><button class="compare" type="button" data-compare="${p.id}">Comparar</button></div></div></article>`}
function renderPromo(){promoCatalog.innerHTML=products.filter(p=>p.offer).slice(0,6).map(productCard).join('')}
function filteredProducts(){const q=(catalogSearch.value||headerSearch.value||'').trim().toLowerCase();let list=products.filter(p=>{const text=`${p.name} ${p.brand} ${p.cpu} ${p.camera}`.toLowerCase();if(q&&!text.includes(q))return false;if(brandFilter.value&&p.brand!==brandFilter.value)return false;if(quickFilter==='offer'&&!p.offer)return false;if(quickFilter==='best'&&!p.bestSeller)return false;if(!['all','offer','best'].includes(quickFilter)&&p.brand!==quickFilter)return false;return true});switch(sortFilter.value){case'brand':list.sort((a,b)=>a.brand.localeCompare(b.brand)||a.name.localeCompare(b.name));break;case'name':list.sort((a,b)=>a.name.localeCompare(b.name));break;case'offer':list.sort((a,b)=>Number(b.offer)-Number(a.offer));break;default:list.sort((a,b)=>Number(b.offer)-Number(a.offer)||Number(b.bestSeller)-Number(a.bestSeller)||a.brand.localeCompare(b.brand));}return list}
function render(){const list=filteredProducts();catalog.innerHTML=list.map(productCard).join('');emptyState.classList.toggle('hidden',list.length>0)}
function populateBrands(){[...new Set(products.map(p=>p.brand))].sort().forEach(b=>{const o=document.createElement('option');o.value=b;o.textContent=b;brandFilter.appendChild(o)})}
function reset(){headerSearch.value='';catalogSearch.value='';brandFilter.value='';sortFilter.value='featured';quickFilter='all';document.querySelectorAll('#quickFilters button').forEach(b=>b.classList.toggle('active',b.dataset.filter==='all'));render()}
function showComparison(){compareContainer.innerHTML=`<div class="compare-grid">${compare.map(p=>`<div class="compare-item"><h3>${escapeHTML(p.name)}</h3><p><b>Cámara:</b> ${escapeHTML(p.camera)}</p><p><b>Procesador:</b> ${escapeHTML(p.cpu)}</p><p><b>RAM:</b> ${escapeHTML(p.ram)}</p><p><b>Almacenamiento:</b> ${escapeHTML(p.storage)}</p><p><b>Batería:</b> ${escapeHTML(p.battery)}</p><p><b>Pantalla:</b> ${escapeHTML(p.screen)}</p></div>`).join('')}</div>`;compareModal.classList.remove('hidden')}
catalog.addEventListener('click',e=>{const b=e.target.closest('[data-compare]');if(!b)return;const p=products.find(x=>x.id===Number(b.dataset.compare));if(!p)return;if(!compare.some(x=>x.id===p.id))compare.push(p);if(compare.length>2)compare.shift();if(compare.length===2)showComparison()});document.getElementById('closeCompare').addEventListener('click',()=>{compare=[];compareModal.classList.add('hidden')});compareModal.addEventListener('click',e=>{if(e.target===compareModal)compareModal.classList.add('hidden')});
[headerSearch,catalogSearch,brandFilter,sortFilter].forEach(el=>el.addEventListener('input',()=>{if(el===headerSearch)catalogSearch.value=headerSearch.value;else if(el===catalogSearch)headerSearch.value=catalogSearch.value;render()}));clearFilters.addEventListener('click',reset);
document.getElementById('quickFilters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;quickFilter=b.dataset.filter;document.querySelectorAll('#quickFilters button').forEach(x=>x.classList.toggle('active',x===b));render()});
document.querySelectorAll('[data-brand-link]').forEach(el=>el.addEventListener('click',()=>{quickFilter=el.dataset.brandLink;brandFilter.value=el.dataset.brandLink;document.querySelectorAll('#quickFilters button').forEach(x=>x.classList.toggle('active',x.dataset.filter===quickFilter));setTimeout(render,0)}));
document.querySelector('[data-category="tablets"]')?.addEventListener('click',e=>{e.preventDefault();headerSearch.value='';catalogSearch.value='';brandFilter.value='';quickFilter='all';document.getElementById('catalogo').scrollIntoView({behavior:'smooth'});render()});
function renderTechnical(){document.getElementById('technicalGrid').innerHTML=technicalProducts.map(p=>`<article class="technical-card"><div class="technical-device ${p.tone}" aria-hidden="true"></div><div class="technical-info"><h3>${escapeHTML(p.name)}</h3><p><b>Procesador:</b> ${escapeHTML(p.cpu)}</p><p><b>Cámara:</b> ${escapeHTML(p.camera)}</p><p><b>Batería:</b> ${escapeHTML(p.battery)}</p><p><b>Pantalla:</b> ${escapeHTML(p.screen)}</p></div></article>`).join('')}
const slides=[...document.querySelectorAll('.hero-slide')],dots=document.getElementById('heroDots');let current=0,timer;slides.forEach((_,i)=>{const d=document.createElement('button');d.type='button';d.ariaLabel=`Promoción ${i+1}`;d.onclick=()=>go(i);dots.appendChild(d)});function go(i){slides[current].classList.remove('is-active');dots.children[current].classList.remove('active');current=(i+slides.length)%slides.length;slides[current].classList.add('is-active');dots.children[current].classList.add('active');clearInterval(timer);timer=setInterval(()=>go(current+1),5500)}document.getElementById('heroPrev').onclick=()=>go(current-1);document.getElementById('heroNext').onclick=()=>go(current+1);go(0);
populateBrands();renderPromo();renderTechnical();render();
